version: '3'

services:
  employee-api:
    image: workfleek-employee-api
    container_name: employee-api
    build: .
    depends_on:
      - employee-db
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080"

  employee-db:
    image: postgres
    container_name: employee-db
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"