version: '3'

services:
  employee-db:
    image: postgres
    container_name: employee-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employee-db
    ports:
      - "127.0.0.1:5432:5432"
