version: '3'

services:
  workfleek-employee-app:
    image: devynlab/workfleek-employee-app:latest
    container_name: workfleek-employee-app
    depends_on:
      - workfleek-employee-db
      - workfleek-keycloak-server
    env_file: employee.env
    ports:
      - "127.0.0.1:8000:8080"
    restart: unless-stopped

  workfleek-employee-db:
    image: postgres
    container_name: workfleek-employee-db
    env_file: employee.env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./employee-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  workfleek-keycloak-server:
    image: quay.io/keycloak/keycloak
    command: [ "start-dev", "--import-realm" ]
    container_name: workfleek-keycloak-server
    depends_on:
      - workfleek-keycloak-db
    env_file: keycloak.env
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./keycloak-realms/:/opt/keycloak/data/import/
    restart: unless-stopped

  workfleek-keycloak-db:
    image: postgres
    container_name: workfleek-keycloak-db
    env_file: keycloak.env
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - ./keycloak-db-data:/var/lib/postgresql/data
    restart: unless-stopped