server:
  port: 8000
  servlet:
    context-path: /api/v1

spring:
  application:
    name: workfleek-employee-app
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/employee-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080/realms/EmployeeRealm